### ISSUE TITLE
Error on message submit without subject

### ISSUE THREAD

**Issue by umdstu** [mailboxer/mailboxer#115]
I implemented a system based off of the example by @RKushnir, and it works. At some point, or since the beginning, submitting a new message without a subject results in a Cannot redirect to nil! error. 

Here is the action:

def create
    recipient_usernames = conversation_params(:recipients).split(',')
    recipients = User.where(:username => recipient_usernames).all

    conversation = current_user.
      send_message(recipients, *conversation_params(:body, :subject)).conversation

    redirect_to conversation
  end

Conversation is nil here, though I dont see why it should be.

Any ideas?

**Comment by deivid-rodriguez** [comment]
Messages now don't require a subject, this can be closed.

**Comment by mices** [comment]
I'm having the same problem If message no longer requires a subject may I see how you would send a message without a subject like `receipt=current_user.send_message(OtherUserObject, 'Test message body')` This gets me wrong number of arguments 2 given min 3 required
