### ISSUE TITLE
How do Notifications work?

### ISSUE THREAD

**Issue by i8ramin** [mailboxer/mailboxer#121]
Hi, I am trying to use this gem in my app for basic user messaging and notifications. I understand how the messaging works between users, but not clear as to how to implement the notifications. I would like to create notifications based on certain user actions. For example, when somebody comments on my post, or likes my post, I should get a notification. I would like to 1) display the notifications within the site header, much like Facebook / Social Stream, etc. 2) send out an email to the user letting them know some activity has taken place on their post.

I have model observers in my code that monitor changes, and I am currently using Pusher to send push notifications to the client, but I'd like to use the Notification features of this gem to store them within a table as well.

Thank you and great work on this gem.
Ramin

**Comment by Frank004** [comment]
@i8ramin can you add a little info on what you did to get the notification in app. I got the mailboxer working like a charm with emails but dont know how to get it to display notification on a dropbox in the header. :/

**Comment by jensitus** [comment]
@Frank004 
With that line of code you can get your unread notifications:
current_user.mailbox.notifications(:read => false)
