### ISSUE TITLE
add columns to migration

### ISSUE THREAD

**Issue by michaelperalta** [mailboxer/mailboxer#128]
I am looking to add two columns to the messages migration so that the messages can accept not only subject and body but also longitude and latitude. I put both in the initial migration and then when I try to submit through the form it say its taking them. When I look at the message in the console it shows !!null and the message.lat will not render anything. What should I do?

**Comment by Alloffices** [comment]
Is this possible or not - seems like there is no way to get other message fields to work properly

**Comment by aysyal31** [comment]
http://stackoverflow.com/questions/25706280/passing-object-with-mailboxer-notification. Refer to my answer for passing objects to notification. 
You can pass lat long as part of the notified object and use it without the need of having migrations in place.
