### ISSUE TITLE
user.mailbox.unread(user).count wrong. not DISTINCT

### ISSUE THREAD

**Issue by i8ramin** [mailboxer/mailboxer#153]
The unread count query does not use DISTINCT, so the result is inaccurate.

    user.mailbox.unread(user).count # returns 3
    user.mailbox.unread(user).all.count # returns 1

Sample SQL generated when doing just count

    SELECT COUNT(*) FROM "conversations" INNER JOIN "notifications" ON 
    "notifications"."conversation_id" = "conversations"."id" AND "notifications"."type" IN
    ('Message') INNER JOIN "receipts" ON "receipts"."notification_id" = "notifications"."id" 
    WHERE "receipts"."mailbox_type" = 'inbox' AND "receipts"."trashed" = 'f' AND 
    "notifications"."type" = 'Message' AND "receipts"."receiver_id" = 33 AND 
    "receipts"."receiver_type" = 'User' AND "receipts"."is_read" = 'f'

**Comment by deivid-rodriguez** [comment]
Just tried this against latest master and it's now using `DISTINCT`. So this has been fixed at some point and can be closed.
