### ISSUE TITLE
Host attachment on amazon S3

### ISSUE THREAD

**Issue by sarunw** [mailboxer/mailboxer#202]
Attachment are set storage as :file, is there a way to override this and host it on amazon s3 ?

**Comment by Abouelsaadat** [comment]
I'm sure you have solved your problem by now, but in case someone stopped by for an another here is what worked for me.

I created the file `app/uploaders/s3_uploader`
```ruby
class S3Uploader < CarrierWave::Uploader::Base
  storage :fog
  def store_dir
    nil
  end
end
```
and in `config/initializers/mailboxer.rb` I added
```ruby
class AttachmentUploader < S3Uploader
end
```
which allows me to inherent from `S3Uploader` to `AttachmentUploader`
and finally I created `config/initializers/carrier_wave.rb` and followed the instructions showed in the [gem page] (https://github.com/carrierwaveuploader/carrierwave/tree/v0.10.0#using-amazon-s3)
