### ISSUE TITLE
Deprecation Warning: The :distinct option for `Relation#count` is deprecated

### ISSUE THREAD

**Issue by loureirorg** [mailboxer/mailboxer#228]
some parts of mailboxer code are calling the deprecated option "distinct". Today this just generate some harmless warnings, but in future versions of Rails (maybe soon) mailboxer may stop work.

```log
DEPRECATION WARNING: The :distinct option for `Relation#count` is deprecated. Please use `Relation#distinct` instead. (eg. `relation.distinct.count`). (called from _app_views_layouts_application_html_erb__2882164410659122302_70190036328360 at /home/daniel/Fontes/camareu/app/views/layouts/application.html.erb:57)

**Comment by fighterii** [comment]
On Rails 5 i encountered this error in two of  my tests:

`  1) Api::V1::MailboxController Message count returns message count
     Failure/Error: self.mailbox.conversations.count(:id, distinct: true)
     
     ArgumentError:
       wrong number of arguments (given 2, expected 0..1)
     # ./app/models/user.rb:86:in `messages_count'
     # ./app/controllers/api/v1/mailbox_controller.rb:52:in `messages_count'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:408:in `call_app!'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:262:in `mock_call!'`

in my user.rb model:

`def messages_count
    self.mailbox.conversations.count(:id, distinct: true)
  end`
On rails 4 this tests are passing.

**Comment by deivid-rodriguez** [comment]
Fixed with Rails 5 support, can be closed.
