### ISSUE TITLE
Exception when using .delay method for Sidekiq (Rails 4.1)

### ISSUE THREAD

**Issue by supremebeing7** [mailboxer/mailboxer#285]
I'm on Rails 4.1, and I've configured the mailers to use UserMailer with this in the `initializers/mailboxer.rb`:

```
config.notification_mailer = UserMailer
config.message_mailer = UserMailer
```

Everything works pretty much as expected. I tried to have the mail jobs done asynchronous using Sidekiq using this code, also in the initializer:

```
config.custom_deliver_proc = ->(mailer, mailable, recipient) do
  mailer.delay.send_email(mailable, recipient)
end
```

However, now when I send a message, I get

```
ArgumentError: undefined class/module Mailboxer::Message
```

Here's the relevant code in user_mailer.rb:

```
def send_email(message, receiver)
  if message.conversation.messages.size > 1
    reply_message_email(message,receiver)
  else
    new_message_email(message,receiver)
  end
end

#Sends an email for indicating a new message for the receiver
def new_message_email(message,receiver)
  @message  = message
  @receiver = receiver
  set_subject(message)
  mail :to => receiver.send(Mailboxer.email_method, message),
     :subject => t('mailboxer.message_mailer.subject_new', :subject => @subject),
     :template_name => 'new_message_email'
end

#Sends and email for indicating a reply in an already created conversation
def reply_message_email(message,receiver)
  @message  = message
  @receiver = receiver
  set_subject(message)
  mail :to => receiver.send(Mailboxer.email_method, message),
     :subject => t('mailboxer.message_mailer.subject_reply', :subject => @subject),
     :template_name => 'reply_message_email'
end
```

I'm not currently using notifications so I haven't included that. Where is it calling Mailboxer::Message, and what arguments does it expect? Is this a Rails 4.1 thing? I'm still pretty new to Ruby/Rails, sorry if this is an obvious error on my part.

I also tried calling `delay` on the individual methods in UserMailer, with the same result:

```
def send_email(message, receiver)
  if message.conversation.messages.size > 1
    UserMailer.delay.reply_message_email(message,receiver)
  else
    UserMailer.delay.new_message_email(message,receiver)
  end
end
```

**Comment by Frank004** [comment]
Hi @supremebeing7  do you have to use configured the mailers to use UserMailer for this to work or can I use normal mailboxer email config. 

I have added this to my initializers/mailboxer.rb
 ```
  config.custom_deliver_proc = ->(mailer, mailable, recipient) do
  mailer.delay.send_email(mailable, recipient)
  end
```
I can send email from my localhost but on production the mail never get sent.

Im using  rails 4.2 and 
```
   gem 'mailboxer', :git => 'https://github.com/mailboxer/mailboxer.git'
````

**Comment by supremebeing7** [comment]
@Frank004 Since it's working locally but not on production, my guess is that something is configured incorrectly with your background processor or Redis on production. Are you using Sidekiq? If so, do you have the Sidekiq::Web console mounted so you can view the processes to see if there are errors?

**Comment by Frank004** [comment]
@supremebeing7  Im using delayed_job

**Comment by supremebeing7** [comment]
I've never used delayed_job, but there should be logs you can view on production to ensure that you aren't getting errors on delayed_jobs getting processed, or that the jobs are even processing.
