### ISSUE TITLE
Rails 4.2 incompatible with Foreigner

### ISSUE THREAD

**Issue by lulalala** [mailboxer/mailboxer#316]
Rails 4.2 comes with its own flavor of `add_foreign_key`. This caused https://github.com/matthuhiggins/foreigner/issues/155

I guess the future plan is to use Rails's own method.

**Comment by mebezac** [comment]
Ran into this issue as well

**Comment by jcoyne** [comment]
Is this still an issue with Foreigner v1.7.2?

**Comment by mebezac** [comment]
Yes even with v1.7.2 I get this error 
`NoMethodError: undefined method `column' for #<Foreigner::ConnectionAdapters::ForeignKeyDefinition:0x007f362c4731a0>
`

**Comment by jcoyne** [comment]
@mebezac what do you do to get that error?

**Comment by jcoyne** [comment]
@mebezac I'm wondering if you saw this comment https://github.com/matthuhiggins/foreigner/issues/161#issuecomment-69549138

**Comment by unhinged** [comment]
I'm getting the same error so I will chime in in case it may help. I was trying to reset my database by running `rake db:drop db:create db:migrate db:seed`. The error occurs during `db:schema:dump`...

    web$ rake db:drop db:create db:migrate db:seed --trace
    ** Invoke db:drop (first_time)
    ** Invoke db:load_config (first_time)
    ** Execute db:load_config
    ** Execute db:drop
    ** Invoke db:create (first_time)
    ** Invoke db:load_config
    ** Execute db:create
    my_database_name already exists
    ** Invoke db:migrate (first_time)
    ** Invoke environment (first_time)
    ** Execute environment
    ** Invoke db:load_config
    ** Execute db:migrate
        ... migrations running ...
    ** Invoke db:_dump (first_time)
    ** Execute db:_dump
    ** Invoke db:schema:dump (first_time)
    ** Invoke environment
    ** Invoke db:load_config
    ** Execute db:schema:dump
    rake aborted!
    NoMethodError: undefined method `column' for #<Foreigner::ConnectionAdapters::ForeignKeyDefinition:0x007fb8d3c2fba8>

**Comment by sergiotapia** [comment]
Hey @lacco is this going to be merged to master soon so I can use the real version of the gem as opposed to:

`gem 'mailboxer', :git => 'git://github.com/div/mailboxer.git', :branch => 'rails42-foreigner'`

**Comment by lacco** [comment]
You can use my branch which is based on current master + the Rails 4.2 foreigner fix: ```gem 'mailboxer', github: 'lacco/mailboxer'```.

**Comment by Mehonoshin** [comment]
Hi!

I'm having the same issue on Rails 4.2 and foreigner 1.7.2

**Comment by joshtate04** [comment]
but there is an issue with underfined local variable 'acts_as_messageable'

**Comment by borenstejn** [comment]
@lacco any news on this soon to be merged in the gem? Thanks!

**Comment by ACPK** [comment]
@lacco Would also love an update.

**Comment by lacco** [comment]
@borenstejn @ACPK I updated my fork to include the newest commits from the last months. 

I would volunteer to make ```mailboxer``` Rails 4.2-compatible, but I am unsure how to solve the ```foreigner``` issue so that we don't break older Rails versions. There are two solutions which come to my mind:

1. We could check for the right Rails version (```Rails.version > "4.2"```), and only then require the ```foreigner``` gem
2. We could make users to require the foreigner gem explicitly if needed (if they are using an older Rails version than 4.2)

**Comment by jcoyne** [comment]
Fixed by #359. Released as 0.13.0

**Comment by sergiotapia** [comment]
:clap:

**Comment by jack-mcgrath** [comment]
Thank you so much!
