### ISSUE TITLE
Article about Mailboxer

### ISSUE THREAD

**Issue by bodrovis** [mailboxer/mailboxer#332]
Hello.

Recently I've written an article for Sitepoint (http://www.sitepoint.com/messaging-rails-mailboxer/) that helps starting off with Mailboxer. Maybe you'd want to add the link to it somewhere in the docs or wiki.

Thank you for the gem!

**Comment by RailsCod3rFuture** [comment]
Hey bodrovis, I have a question. How can I swap out gravatar for refile gem? When I try to add the new functionality, it gives me a multiple argument error. https://github.com/elabs/refile Can you post the updated methods for me? to replace the methods below. Any others that I haven't seen while trying to update your solution. Thanks!

def gravatar_for(user, size = 30, title = user.username)
    image_tag  gravatar_image_url(user.email, size: size), title: title, class: 'img-rounded'
  end

<%= gravatar_for participant %>

<%= gravatar_for message.sender, 45, message.sender.username %>

**Comment by bodrovis** [comment]
@RailsCod3rFuture Okay, I will try to implement that on a separate branch. Please discuss in this issue https://github.com/bodrovis/SitePoint-Mailboxer/issues/1 as it is not related to the Mailboxer gem itself.

**Comment by Frank004** [comment]
@bodrovis I just need to thank you I got one working before but now with this tut I can get it like I want it :+1:  so happy thnk you Have you try adding search ??

**Comment by bodrovis** [comment]
@Frank004 Oh, thank you :) Well, I haven't tried that but I have some articles on real-time updates (chat app is used as an example), see here: http://www.sitepoint.com/author/ibodrov/

**Comment by Frank004** [comment]
@bodrovis  Cool I bookmark every article :) :+1: .  I copy de controllers a views and helpers  to my app just to try it everthing works fine as the demo just got one error on when creating a new message. uninitialized constant Message.

**Comment by bodrovis** [comment]
@Frank004 As this is not related to the Mailboxer itself, please open a new issue https://github.com/bodrovis/SitePoint-Mailboxer/issues here and provide error log so that I can check.

**Comment by marcfuentes** [comment]
thanks for this much needed tutorial bodrovis

**Comment by mices** [comment]
I'm having the problem  that sent messages to create a new conversation don't cause 2 inserts into mailboxer_receipts, only 1 This results in sent messages not appearing in the receivers mailbox as there's no insert to the mailboxer_receipts table for the recipients receiver_id 

 <%= link_to (t 'send_message'), new_conversation_path(name: @user.name) %>

<% name = @recipients.name %>
<%= (t 'starting_a_conversation_with') %><%= " " %><b><%= name %></b>
<br><br>
<%= form_tag conversations_path, method: :post do %>
  <div class="form-group">
    <%= label_tag 'subject', 'Subject' %>
    <%= text_field_tag 'subject', nil, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'body', 'Message' %>
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= hidden_field_tag 'recipients', @recipients, class: 'form-control' %>
  </div>

  <%= submit_tag 'Send', class: 'btn btn-primary' %>
<% end %>

  def new
   @recipients = User.find_by_name(params[:name])
  end

  def create
    recipients = params[:recipients]
    receipt = current_user.send_message(recipients, params[:body], params[:subject])
    flash[:success] = "Message has been sent!"
    redirect_to conversation_path(receipt.conversation)
  end
