### ISSUE TITLE
message.is_read?(user) should return boolean without the user object

### ISSUE THREAD

**Issue by mirfan899** [mailboxer/mailboxer#336]
For example I'm getting the inbox of the user i.e.

```
conversations = current_user.mailbox.conversations
convesations.messages.first.is_read?(current_user)
```

We know we have pulled the mailbox of the  `current_user` so there is no point to pass the object to
`is_read?` method to get the boolean.

method should be message.is_read? it will return boolean. Same case is with message.is_unread? also.

**Comment by sungwoncho** [comment]
What if you want to see if the message is read by a `messageable` object other than `current_user`?
