### ISSUE TITLE
recipients should return the receiver(s) of the message or conversation

### ISSUE THREAD

**Issue by mirfan899** [mailboxer/mailboxer#337]
While getting the recipients of conversation, in recipients response there is also sender present.

```
alfa.send_message(beta, "Body", "subject")
beta.mailbox.conversations.find(1).recipients
[#<User id: 1, email: "alfa@gmail.com", created_at: "2015-03-03 06:04:30", updated_at: "2015-03-03 14:27:50">,
 #<User id: 2, email: "beta@gmail.com", created_at: "2015-02-16 14:21:12", updated_at: "2015-02-26 12:36:45">]

beta.mailbox.conversations.find(1).messages.first
 #<Mailboxer::Message id: 1, type: "Mailboxer::Message", body: "Body", subject: "Subject", sender_id: 1, sender_type: "User", conversation_id: 1, draft: false, notification_code: nil, notified_object_id: nil, notified_object_type: nil, attachment: nil, updated_at: "2015-03-04 06:51:45", created_at: "2015-03-04 06:51:45", global: false, expires: nil>

beta.mailbox.conversations.find(1).messages.first.receipts
[#<User id: 1, email: "alfa@gmail.com", created_at: "2015-03-03 06:04:30", updated_at: "2015-03-03 14:27:50">,
 #<User id: 2, email: "beta@gmail.com", created_at: "2015-02-16 14:21:12", updated_at: "2015-02-26 12:36:45">]
```

This should only return the `alfa` user instead of both. Same with the case of `receipts` method.

**Comment by sungwoncho** [comment]
I don't think it should. For instance, in `beta.mailbox.conversations.find(1).recipients`, you are calling `#recipients` on a `Conversation` object. The conversation is two-way, and indeed has two recipients.

**Comment by mirfan899** [comment]
You are write about the conversation, but I'm talking about the message object. When you fetch the message and wants to know who is the the receiver of this message, instead of returning the receiver it returns both sender and receiver.

**Comment by aoozdemir** [comment]
This should definitely be the way @mirfan899 describes, or at least some other method should exist for this purpose only.

A workaround for this is to define recipient like this in your controller and I don't think this is efficient enough.
```ruby
@recipient = (@conversation.recipients - [current_user])
```
