### ISSUE TITLE
Dependent Destroy feature should be added for models.

### ISSUE THREAD

**Issue by mirfan899** [mailboxer/mailboxer#339]
Is there anything available for destroying all the messages when a user is deleted from Database?

```
class User < ActiveRecord::Base
  acts_as_messageable
end
```

there should be something like dependent destroy feature for gem. Currently when a user is deleted from db it's conversations are still there.

**Comment by sungwoncho** [comment]
Sounds good to me. Are you saying that, for instance, `belongs_to :receiver, :polymorphic => :true` in `receipt.rb` should have `dependent: :destroy` option?

**Comment by mirfan899** [comment]
I didn't go deep into the gem code, suppose I've two different models in my app i.e. `User` and `Group`, both can send and receive messages. When a user is deleted from db then there should not be the messages available for that user, same case for the `Group` model. It's like other relationships we define for models and when an object is deleted it's dependent objects should also be deleted.

**Comment by sungwoncho** [comment]
Actually, scratch what I said. It will destroy the `receiver` when `receipt` gets destroyed, and will leave all the other `receipt` that belong to the `receiver` orphaned. `dependent: :destroy` should be added on the other side of the association, namely in `receiver`.

**Comment by Frank004** [comment]
did you get any work around for this??

**Comment by jerefrer** [comment]
I just added `before_destroy { messages.destroy_all }`:

````ruby
class User < ActiveRecord::Base
  acts_as_messageable
  before_destroy { messages.destroy_all }
end
````

Do you think it's enough ? If it is maybe it would be sufficient to add it to the README instead of adding an option to the gem.

**Comment by Frank004** [comment]
thank you ill try it out and let you know.

**Comment by seanpaulkelley** [comment]
thank you ill try it out and let you know.
I am very interested in the way to do this too.

**Comment by ACPK** [comment]
@seanpaulkelley - Did it work?
