### ISSUE TITLE
"Deleted" scope - Active Record 4.2.0 already defined a class method with the same name.

### ISSUE THREAD

**Issue by souqueta** [mailboxer/mailboxer#340]
Hi,

Currently in the process of migrating from Rails 3.2 to Rails 4.2, I have the following error
after deploying on Heroku, while launching.

<code>
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/scoping/named.rb:147:in `scope': You tried to define a scope named "deleted" on the model "Mailboxer::Receipt", but Active Record already defined a class method with the same name. (ArgumentError)

from /app/vendor/bundle/ruby/2.2.0/gems/mailboxer-0.12.5/app/models/mailboxer/receipt.rb:28:in `<class:Receipt>'

</code>

Strangely, I don't have the error at all when running rails locally.

A similar issue has been encountered there: 
http://stackoverflow.com/questions/24407912/scope-and-class-method-with-the-same-name

Any help is appreciated,

**Comment by jcoyne** [comment]
You're probably encountering this when deployed because Rails does autoloading in development, but eager loading in production. You can find out where that method is defined by doing:  `Receipt.methods(:deleted).source_location` in rails console.

**Comment by souqueta** [comment]
Thanks for you answer, I get:

<code>
Receipt.methods(:deleted).source_location
NameError: uninitialized constant Receipt 
</code>

and

<code>
load ('/usr/local/lib/ruby/gems/2.2.0/gems/mailboxer-0.12.5/app/models/mailboxer/receipt.rb')
ArgumentError: You tried to define a scope named "deleted" on the model "Mailboxer::Receipt", but Active Record already defined a class method with the same name.
</code>

**Comment by jcoyne** [comment]
Sorry, try this: `Mailboxer::Receipt.methods(:deleted).source_location`

Also, why are you doing a `load` on the receipt.rb file? That will trigger a second evaluation of the file and may be what is causing the problem.

**Comment by souqueta** [comment]
Mailboxer::Receipt.method(:deleted).source_location
=> ["/usr/local/lib/ruby/gems/2.2.0/gems/permanent_records-3.2.0/lib/permanent_records.rb", 184]

It's used in permanent_records gem which seems outdated.

Thanks.

**Comment by souqueta** [comment]
Took the permission to close the issue since not specific to Mailboxer.

However, this would be nice to have a fix for it.

Created a patch there: https://github.com/mailboxer/mailboxer/compare/master...souqueta:patch-1
