### ISSUE TITLE
How to send different notification types?

### ISSUE THREAD

**Issue by rgo** [mailboxer/mailboxer#342]
Hi,

  I'm using notifications' mailboxer for system messages in our application. Now I need to send other kinds of notifications i.e.:
  - Updates
  - Tips
  - Activities
  - ...

I was reviewing notifications code and I read about notified_object and notification_code.
What is notification_code for? I don't see any usage in the code, logs (when I send notifications) or social_stream.

In the meantime, I guess I can achieve it with notified_object by creating a a NotificationType model, create notification types there and pass the instance of this model to notifications. Is it the correct approach?

Thanks!

**Comment by jakeatwork** [comment]
I was going through the same process and I found Jamie's answer on this (2nd answer down) very useful. Got everything working for me, though it requires modifying the code of the gem a bit. You can see my modifications at http://github.com/jakeatwork/mailboxer

http://stackoverflow.com/questions/22914420/adding-belongs-to-relationship-to-ruby-gem-mailboxer

If I remember right, the notified object code was deprecated and/or documentation was non-existent, though it's been a while. Let me know if you need more detail. Happy to help.

**Comment by rgo** [comment]
Thanks @jakeatwork 
Your modifications is similar to notified_object current implementation (a polymorphic belongs_to and some scopes).

notified_object not seems be deprecated to me but maybe you says it because this commit: https://github.com/mailboxer/mailboxer/commit/e54ee75bc9cc147f7a1f042f6aa370cd8a53529d

It only warnings about deprecate "object" method.
