### ISSUE TITLE
Rails 4.2 support

### ISSUE THREAD

**Issue by stefanvermaas** [mailboxer/mailboxer#348]
Hi guys,
I was wondering; is support for Rails 4.2 coming? And when will the new gem version be pushed to rubygems.org?
Cheers!

**Comment by jcoyne** [comment]
Rails 4.2 will be supported as soon as someone does the work and submits a pull request. There's no one actively supporting this gem right now. I'm happy to merge PRs and cut releases, but I don't have time to develop this.

**Comment by viktorchukhantsev** [comment]
Contact with author github.com/div/mailboxer

**Comment by jcoyne** [comment]
fixed by #359, released as 0.13.0

**Comment by stefanvermaas** [comment]
Thanks @jcoyne for the heads up!
