### ISSUE TITLE
undefined local variable or method

### ISSUE THREAD

**Issue by HuckyDucky** [mailboxer/mailboxer#357]
I can't add ```acts_as_messageable``` to *anything*.

    NameError: undefined local variable or method `acts_as_messageable' for #<Class:0x007fa14d118bb8>

Rails 4.2 has been out for a while now. I had to use @lacco's fork to fix the Foreigner issue, but this problem is on both of them.

Note that spinning up a brand new application and adding ```acts_as_messageable``` works fine. But there's obviously something interfering here.

**Comment by deivid-rodriguez** [comment]
This seems very outdated. I'd close and let the OP reopen if it can be reproduced in recent versions.
