### ISSUE TITLE
Error 'cannot load such file -- fog'

### ISSUE THREAD

**Issue by cavalryjim** [mailboxer/mailboxer#362]
After adding "gem 'mailboxes', '0.13.0' " to my gemfile and successfully running 'bundle install', I attempt to run 'rails g mailboxes:install' and receive the following error:

   /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- fog (LoadError)from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:3:in `<top (required)>'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/carrierwave-0.10.0/lib/carrierwave/storage.rb:9:in `<top (required)>'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/carrierwave-0.10.0/lib/carrierwave.rb:78:in `<top (required)>'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/mailboxer-0.13.0/lib/mailboxer/engine.rb:3:in `<top (required)>'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/mailboxer-0.13.0/lib/mailboxer.rb:41:in `<top (required)>'
	from /Users/james/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/james/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/james/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/james/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/james/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /Users/james/Projects/damage_list/config/application.rb:7:in `<top (required)>'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/spring-1.3.6/lib/spring/application.rb:82:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/spring-1.3.6/lib/spring/application.rb:82:in `preload'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
	from /Users/james/.rvm/gems/ruby-2.2.2@damage_list/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/james/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/james/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'	from -e:1:in `<main>'

**Comment by onlinetocode** [comment]
According to the docs you have to run `rails g mailboxer:install`and not `rails g mailboxes:install`. Maybe it is caused by your typo.

**Comment by deivid-rodriguez** [comment]
This seems unrelated to mailboxer. Let's close.
