### ISSUE TITLE
Finding a conversation by recipients

### ISSUE THREAD

**Issue by chrise86** [mailboxer/mailboxer#389]
I have a controller action where I find a `Councillor`, and I need to find or create a conversation between the `current_user` and the `@councillor`.

So theoretically something like this:

```
@councillor = Councillor.find params[:id]
@conversation = current_user.mailbox.conversations.where(recipients: @councillor)
```

**Comment by andrezimpel** [comment]
+1

**Comment by soyellupi** [comment]
+1
