### ISSUE TITLE
Rails 5: ActiveModel::UnknownAttributeError at /messages unknown attribute 'delivery_method' for Mailboxer::Receipt.

### ISSUE THREAD

**Issue by cjjuice** [mailboxer/mailboxer#391]
Rails 5 error:

ActiveModel::UnknownAttributeError at /messages
unknown attribute 'delivery_method' for Mailboxer::Receipt.

Seems to be coming from lib/mailboxer/mail_dispatcher.rb 

```ruby
 def default_send_email(receipt)
      mail = mailer.send_email(mailable, receipt.receiver)
      mail.respond_to?(:deliver_now) ? mail.deliver_now : mail.deliver
      receipt.assign_attributes(
        :delivery_method => :email,
        :message_id => mail.message_id
      )
      mail
    end
```

**Comment by VicML** [comment]
In december was a update, I do  `rails g mailboxer:install` to generate the migration `add_delivery_tracking_info_to_mailboxer_receipts` , (i skip overwrite config/initializers/mailboxer.rb).

**Comment by cjjuice** [comment]
@VicML Thanks!
