### ISSUE TITLE
Message#delivery doesn't return a validated receipt.

### ISSUE THREAD

**Issue by daslicious** [mailboxer/mailboxer#394]
https://github.com/mailboxer/mailboxer/blob/master/app%2Fmodels%2Fmailboxer%2Fmessage.rb#L36

On that line, the loop breaks after the first receipt fails validation.  Since `sender_receipt` is the last element in `tmp_receipts`, `sender_receipt` won't have `validate` called on it if a previous receipt fails `validate`.

This means the receipt returned by `Messageable#send_message`, won't have errors on it even if it isn't valid.

Am I missing something or should we make sure `Messageable#send_message` returns a validated receipt?  We could just prepend instead of append `sender_receipt` to `tmp_receipts`.

**Comment by pastDexter** [comment]
Last merge request solved this problem #412

**Comment by deivid-rodriguez** [comment]
This was fixed by the linked PR, let's close it!
