### ISSUE TITLE
Rails 5 ArgumentError message count distinct

### ISSUE THREAD

**Issue by fighterii** [mailboxer/mailboxer#407]
On Rails 5 i encountered this error in two of  my tests:
```
1) Api::V1::MailboxController Message count returns message count
   Failure/Error: self.mailbox.conversations.count(:id, distinct: true)
   ArgumentError:
   wrong number of arguments (given 2, expected 0..1)
    # ./app/models/user.rb:86:in `messages_count'
    # ./app/controllers/api/v1/mailbox_controller.rb:52:in `messages_count'
    # /usr/local/rvm/gems/ruby-2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:408:in `call_app!'
    # /usr/local/rvm/gems/ruby-2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:262:in `mock_call!'
```

in my user.rb model:

`def messages_count
    self.mailbox.conversations.count(:id, distinct: true)
  end`
On rails 4 this tests are passing.

I assume this is related to [#228](https://github.com/mailboxer/mailboxer/issues/228), but as it is now an error and not a warning, i opened up a new issue.

**Comment by deivid-rodriguez** [comment]
Fixed with Rails 5 support, can be closed.
