### ISSUE TITLE
Rails 5 uniq is deprecated

### ISSUE THREAD

**Issue by fighterii** [mailboxer/mailboxer#408]
I get the following deprecation warning on `rails 5.0.0.beta3`:

`DEPRECATION WARNING: uniq is deprecated and will be removed from Rails 5.1 (use distinct instead). (called from block in <class:Conversation> at /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/mailboxer-99d16871375c/app/models/mailboxer/conversation.rb:18)`

**Comment by cantonic** [comment]
I have created a PR https://github.com/mailboxer/mailboxer/pull/419
