### ISSUE TITLE
[Rails5] Conversation not being save when using send_message

### ISSUE THREAD

**Issue by jeremymarc** [mailboxer/mailboxer#410]
I'm using Rails 5 with the last mailboxer gem (from github) and I have a weird behavior:
Mailboxer::Receipt.count => 0
User.first.send_message(User.last, 'body', 'subject')
Mailboxer::Receipt.count => 0
Mailboxer::Conversation.count => 0

But if I do: 
User.first.send_message(User.last, 'subject', 'body').notification.conversation.save
Mailboxer::Conversation.count => 1

**Comment by pastDexter** [comment]
I have the same problem on the new version of Rails 4.

**Comment by gycn** [comment]
Same problem here. The same thing happens with notifications too.

**Comment by jeremymarc** [comment]
@gycn I fixed it in this PR https://github.com/mailboxer/mailboxer/pull/420

**Comment by gycn** [comment]
Alright, thank you. I think the sender field should also be optional in addition to the notification object based on the way the Messageable.notify method works

**Comment by deivid-rodriguez** [comment]
This seems to have been fixed by related PR's, let's close.
