### ISSUE TITLE
Email is sent to the sender of the message

### ISSUE THREAD

**Issue by pastDexter** [mailboxer/mailboxer#411]
After changes that were made in the commit [Add Message-ID Tracking on receipts](https://github.com/mailboxer/mailboxer/commit/2e30b5cb4990bde00be5253667c864343f52f255) every time someone creates new message or reply to one, a notification email is also sent to him. 

```ruby
# app/models/mailboxer/message.rb:32

sender_receipt = build_receipt(sender, 'sentbox', true)

temp_receipts << sender_receipt

if temp_receipts.all?(&:valid?)
Mailboxer::MailDispatcher.new(self, temp_receipts).call if send_mail
```

The problem is that `Mailboxer::MailDispatcher` receives `tmp_receipts` that includes `sender_receipt`

**Comment by deivid-rodriguez** [comment]
This was fixed by the attached PR. Let's close it!

**Comment by deivid-rodriguez** [comment]
@jcoyne Ping, you probably missed my last message :)
