### ISSUE TITLE
Multiple attachments are allowing in Mailboxer?

### ISSUE THREAD

**Issue by sathishcel** [mailboxer/mailboxer#417]
Tell me that Mailboxer is allowing Multiple attachment or not?

I am trying 
 <%= f.file_field "attachment" , class:"form-control", multiple: true %> But it not allowing at same time I can attach single file and send email.

**Comment by caJaeger** [comment]
https://github.com/mailboxer/mailboxer/issues/344

**Comment by jcoyne** [comment]
Closed duplicate of #344
