### ISSUE TITLE
Need help in dropping the mailboxer tables

### ISSUE THREAD

**Issue by suramai** [mailboxer/mailboxer#422]
This is my migration

class DropMailboxerReceipts < ActiveRecord::Migration[5.0]
  def change
    drop_table :mailboxer_receipts
    drop_table :mailboxer_notifications
    drop_table :mailboxer_conversations
    drop_table :mailboxer_conversation_opt_outs
  end
end

And I am getting these errors.

Running rails db:migrate on ⬢ fat-hre-434... up, run.6654
   (1.2ms)  SELECT pg_try_advisory_lock(2008333635372579375);
  ActiveRecord::SchemaMigration Load (0.8ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Migrating to DropMailboxerReceipts (20160629211944)
   (2.6ms)  BEGIN
== 20160629211944 DropMailboxerReceipts: migrating ============================
-- drop_table(:mailboxer_receipts)
   (6.0ms)  DROP TABLE "mailboxer_receipts"
   -> 0.0065s
-- drop_table(:mailboxer_notifications)
   (4.0ms)  DROP TABLE "mailboxer_notifications"
   -> 0.0053s
-- drop_table(:mailboxer_conversations)
   (2.2ms)  DROP TABLE "mailboxer_conversations"
   (0.8ms)  ROLLBACK
   (1.0ms)  SELECT pg_advisory_unlock(2008333635372579375)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DependentObjectsStillExist: ERROR:  cannot drop table mailboxer_conversations because other objects depend on it
DETAIL:  constraint mb_opt_outs_on_conversations_id on table mailboxer_conversation_opt_outs depends on table mailboxer_conversations
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
: DROP TABLE "mailboxer_conversations"
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:146:in `drop_table'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:845:in `block in method_missing'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:814:in `block in say_with_time'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:814:in `say_with_time'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:834:in `method_missing'
/app/db/migrate/20160629211944_drop_mailboxer_receipts.rb:5:in `change'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:788:in `exec_migration'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:772:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:771:in `block in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:770:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:950:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1211:in `block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1279:in `block in ddl_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/transactions.rb:211:in `transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1279:in `ddl_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1210:in `execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1183:in `block in migrate_without_lock'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1182:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1182:in `migrate_without_lock'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1131:in `block in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1298:in `with_advisory_lock'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1131:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1005:in `up'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:983:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands.rb:18:in `<top (required)>'
/app/bin/rails:4:in `require'
/app/bin/rails:4:in `<main>'
ActiveRecord::StatementInvalid: PG::DependentObjectsStillExist: ERROR:  cannot drop table mailboxer_conversations because other objects depend on it
DETAIL:  constraint mb_opt_outs_on_conversations_id on table mailboxer_conversation_opt_outs depends on table mailboxer_conversations
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
: DROP TABLE "mailboxer_conversations"
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:146:in `drop_table'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:845:in `block in method_missing'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:814:in `block in say_with_time'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:814:in `say_with_time'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:834:in `method_missing'
/app/db/migrate/20160629211944_drop_mailboxer_receipts.rb:5:in `change'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:788:in `exec_migration'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:772:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:771:in `block in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:770:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:950:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1211:in `block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1279:in `block in ddl_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/transactions.rb:211:in `transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1279:in `ddl_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1210:in `execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1183:in `block in migrate_without_lock'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1182:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1182:in `migrate_without_lock'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1131:in `block in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1298:in `with_advisory_lock'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1131:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1005:in `up'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:983:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands.rb:18:in `<top (required)>'
/app/bin/rails:4:in `require'
/app/bin/rails:4:in `<main>'
PG::DependentObjectsStillExist: ERROR:  cannot drop table mailboxer_conversations because other objects depend on it
DETAIL:  constraint mb_opt_outs_on_conversations_id on table mailboxer_conversation_opt_outs depends on table mailboxer_conversations
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.rc2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:146:in `drop_table'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:845:in `block in method_missing'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:814:in `block in say_with_time'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:814:in `say_with_time'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:834:in `method_missing'
/app/db/migrate/20160629211944_drop_mailboxer_receipts.rb:5:in `change'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:788:in `exec_migration'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:772:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:771:in `block in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:770:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:950:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1211:in `block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1279:in `block in ddl_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/transactions.rb:211:in `transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1279:in `ddl_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1210:in `execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1183:in `block in migrate_without_lock'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1182:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1182:in `migrate_without_lock'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1131:in `block in migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1298:in `with_advisory_lock'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1131:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:1005:in `up'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/migration.rb:983:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands.rb:18:in `<top (required)>'
/app/bin/rails:4:in `require'
/app/bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
suramai@rails-tutorial:~/workspace/converse (master) $ 

Can someone help me drop the mailboxer tables?

**Comment by dom-dom-dom** [comment]
Hello. I have no experience with this as I am just evaluating mailboxer for my project.  However, the error advises you to use cascade. Have you tried this yet?

HINT: Use DROP ... CASCADE to drop the dependent objects too.

This link may help: http://stackoverflow.com/questions/16928668/rails-create-a-drop-table-cascade-migration

good luck!

**Comment by deivid-rodriguez** [comment]
Yep, @dom-dom-dom is one solution. Another one would be to drop first `mailboxer_conversations_opt_outs`. In any case, I think this can be closed.
