### ISSUE TITLE
Save a message as draft is possible using this gem?

### ISSUE THREAD

**Issue by kanagarajuror** [mailboxer/mailboxer#424]

**Comment by deivid-rodriguez** [comment]
I don't think this is provided out of the box, you'll probably have to build it yourself.

**Comment by kanagarajuror** [comment]
Thanks for the response David.

Regards
Kanagaraju

**Comment by deivid-rodriguez** [comment]
You're welcome. Can you close the issue?

**Comment by kanagarajuror** [comment]
Sure
