### ISSUE TITLE
how to integrate mailboxer with rails5

### ISSUE THREAD

**Issue by ajazshaik** [mailboxer/mailboxer#432]

**Comment by deivid-rodriguez** [comment]
I don't think there's any special considerations for Rails 5.

I'd close this since it's just a support question.

**Comment by alexung** [comment]
@ajazshaik I'm currently using rails 5 and it works for me.

**Comment by bodrovis** [comment]
I can confirm that it does work with Rails 5. Here is an article about Mailboxer https://www.sitepoint.com/messaging-rails-mailboxer/

**Comment by codered** [comment]
I am using it in rails 5, you can close this thread.

**Comment by jasdeepsingh** [comment]
Works well with Rails 5 for me too.
