### ISSUE TITLE
Inbox count Mailboxer

### ISSUE THREAD

**Issue by ajazshaik** [mailboxer/mailboxer#434]
How to display my gmail inbox count in rails app

just want to display of my gmail inbox  badge with count in rails app
![untitled](https://cloud.githubusercontent.com/assets/18135790/17395659/3edf8b1c-5a4d-11e6-8fd6-416a69b88f5c.png)

**Comment by deivid-rodriguez** [comment]
I guess you want to use something like this: https://github.com/mailboxer/mailboxer/blob/master/lib/mailboxer/models/messageable.rb#L47-L51.

I guess this can be closed since this is just a question, not an issue.

**Comment by ajazshaik** [comment]
URL you have provided is ok, but i wanna integrate my gmail inbox to load smtp/pop3 settings

**Comment by deivid-rodriguez** [comment]
Sorry, I think that has nothing to do with what `mailboxer` does.
