### ISSUE TITLE
Get a conversation between only two users

### ISSUE THREAD

**Issue by tonyvince** [mailboxer/mailboxer#469]
What is the best of retrieving a conversation between a user A and B that doesn't include any other users?

**Comment by jodyheavener** [comment]
Just happened to be looking for the same thing, and it appears there's a method called `conversations_with`:

```shell
user_one.mailbox.conversations_with(user_two)
=> #<ActiveRecord::Relation [#<Mailboxer::Conversation id: 1 ... >]>
```

**Comment by tonyvince** [comment]
https://github.com/mailboxer/mailboxer/pull/470

**Comment by sidneyjohndiongzon** [comment]
user_one.mailbox.conversations_with(user_one) also returns some same data  from user_one.mailbox.conversations_with(user_two)
