### ISSUE TITLE
Migrating on Oracle database

### ISSUE THREAD

**Issue by mikevoets** [mailboxer/mailboxer#478]
Oracle databases only allows index names to be up to 30 characters. When I run `rake db:migrate`, I get the following error:

```
ArgumentError: Index name 'mailboxer_notifications_notified_object' on table 'mailboxer_notifications' is too long; the limit is 30 characters
.../db/migrate/20180408000035_create_mailboxer.mailboxer_engine.rb:23:in `up'
```

**Comment by jcoyne** [comment]
This is an issue in Rails, not something we can fix in this gem.  See discussion here: https://github.com/rails/rails/pull/1993

**Comment by mikevoets** [comment]
It may be an issue in Rails, but it is definitely something you can fix for this Gem by shortening the index name.

**Comment by jcoyne** [comment]
@mikevoets You can update your own migrations as you see fit in your local install.  I don't want to support the particularities of every RDBMS here.
