### ISSUE TITLE
Send from multiple profiles

### ISSUE THREAD

**Issue by joshm1204** [mailboxer/mailboxer#498]
Case:
User A has 3 Prolies, of different models, Car, Truck, Bike
User B has 2 Profiles of models, Bike and Truck

I need User A’s truck profile to be able to email user b’s bike profile.  

Then when each user goes into their mailbox they see all the messages in inbox associates with all profiles and if they click to see message it shows the FROM box as profile truck Id and the TO box as profile bike id.

How can this be accomplished?

**Comment by yoshie902a** [comment]
Request to close this issue
