### ISSUE TITLE
Sending messages without a subject

### ISSUE THREAD

**Issue by damien** [mailboxer/mailboxer#65]
Hey guys!

First off, thanks for mailboxer. Great piece of work!

That being said, is there any particular reason why a `subject` is required to send a message? I have a requirement to send messages without requiring a subject and ended up overriding the default `send_message` method like so:

``` ruby
# Override's Mailboxer's #send_message such that subjects are not required.
# @see https://github.com/ging/mailboxer/blob/56987403939d6077ddb72bc708df90ab6e672ab6/lib/mailboxer/models/messageable.rb#L48-57
# @param [Hash] opts An options hash used to configure and send a message
# @option [User, Array<User>] :to Users to send a message to
# @option [String] :subject An optional subject for this message (nil)
# @option [File] :attatchment An optional attatchment to include with this message (nil)
# @options [Boolean] :sanitize Weather or not to sanetize input (true)
def send_message(opts = {})
  recipients = opts.delete(:to)
  subject    = opts.delete(:subject) || ""
  body       = opts.delete(:body)
  attachment = opts.delete(:attatchment)
  sanitize   = opts.delete(:sanitize) || true

  convo = Conversation.new(subject: subject)

  message = messages.new(body: body, subject: subject, attachment: attachment)
  message.conversation = convo
  message.recipients = recipients.is_a?(Array) ? recipients : [recipients]
  message.recipients = message.recipients.uniq

  message.deliver(false, sanitize)
end
```
### Here's what I'm wondering:
1. Will this cause any issues with Mailboxer's data model?
2. Are there any implications to making a subject optional that I should consider or be aware of?
3. If everything here checks out, would you guys be open to me submitting this as a patch to[ `send_message`](https://github.com/ging/mailboxer/blob/56987403939d6077ddb72bc708df90ab6e672ab6/lib/mailboxer/models/messageable.rb#L48-57)?

**Comment by Joe312341** [comment]
Was this change ever submitted (ability to reply without a subject) ?

**Comment by stevelacey** [comment]
Anyone reading – I opt for setting the subject to `-` and then never showing it anywhere.

¯\_(ツ)_/¯
