### ISSUE TITLE
How to mark a conversation as read?

### ISSUE THREAD

**Issue by sennor** [mailboxer/mailboxer#89]
I use this method to count unread messages:
`
 def count_msg
  if current_user
   @unread_count = mailbox.inbox(:is_read => true).count(:id, :distinct => true).to_s
  end
  end`

In my conversation controller I have:
`
 def show
    conversation.mark_as_read(current_user)
  end`

And I get this error in view:
`Can't mass-assign protected attributes: is_read`

I have created a test account and sent it 1 message. But after I have seen the message/conversation there is still 1 unread message. How can that be?

**Comment by hammadxcm** [comment]
SO any solution?
```
module MailboxHelper
  def unread_messages_count
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end
```
wrong number of arguments (given 2, expected 0..1)
what solution you suggest?
