### ISSUE TITLE
1 conversation between users

### ISSUE THREAD

**Issue by ndreckshage** [mailboxer/mailboxer#95]
Has anyone had any luck with limiting conversations to one between 2 users? so its more like IM rather than emailing. i was experimenting a bit and have this  (havent refactored into controller/helpers yet)

( i have a list of users, for each user i want to display a link to open a preexisting conversation if one exists, or a link to create a new one if one doesnt exist, which then opens via ajax in a twitter bootstrap modal)

``` erb
      <% @users.each do |user| %>
        <li>
          <%= link_to user.name, user %>
          <% if @mailbox.conversations.map { |c| c.receipts.where(receiver_id: user) }.flatten.present? %>
            <% @mailbox.conversations.each do |conversation| %>
              <% conversation.participants.each do |participant| %>
                <% if participant == user && participant != current_user %>
                  <%= link_to "Open Conversation", conversation, class: "btn", data: { toggle: "modal", target: "#conversation_modal" } , remote: true %>
                <% end %>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to 'Send Message', new_conversation_path(recipient: user.id), class: "btn", data: { toggle: "modal", target: "#conversation_moda" } , remote: true %>
          <% end %>
        </li><br>
      <% end %>
```

so this all works, but when you create a new message and close the modal without refreshing -- i dont ajax replace that link (i could) on the view layer, but this is a work around -- so you can click the link again, and create a new message rather than reop. then when you refresh, you would see 2 links to open conversations since there are now 2.

anyone have a good idea on how to change the model/controller so only 1 conversation per user pair could enter the db?

**Comment by jesalg** [comment]
What's a good approach for retrieving a conversation just between two participants with ActiveRecord? 

I'm doing something like this but it's not very performant:

    Mailboxer::Conversation.between(u1, u2).find{|c| c.participants.count == 2 }

Query by @ariabov doesn't exactly work right if there are many conversations between u1, u2 AND others. It fetches all of them instead of just the ones that are between only u1 and u2.

**Comment by Gordensen** [comment]
Hi! I need to find a way to get the conversation (if exists) between exactly N participants. 

For example, if I have a conversation CONV1 between U1, U2 and U3 and also exists a conversation CONV2 between U1 and U2 when I look for a conversation between U1, U2, U3 I expect to receive just CONV1

Any help is appreciated!!!!
Thanks

**Comment by tonyvince** [comment]
Is there any performant way of retrieving a conversation between only two participants A and B ?

**Comment by freeslugs** [comment]
@tonyvince 
the latest pr solves this. `only_between` works perfectly;

e.g. 
```ruby
Mailboxer::Conversation.between(user1, user2)
# returns convos between these two users
```

**Comment by john-lanticse** [comment]
@freeslugs how do i use only_between? I already have a `mailboxer 0.15.1` but I get an undefined method error `only_between`

**Comment by freeslugs** [comment]
something like this: 
```ruby
conversations = Mailboxer::Conversation.only_between(user1, user)
```

apparently i'm using `mailboxer (0.15.1)`

**Comment by sidneyjohndiongzon** [comment]
Mailboxer::Conversation.between(user1, user1) returns also the conversation between user1 and user2
